# Disable Jekyll processing for pure static site
markdown: kramdown
highlighter: rouge

# Site settings
title: CyberSecurity Compass
description: Advanced cybersecurity assessment and compliance framework
url: "https://bharathk2498.github.io"
baseurl: "/CyberSecurityCompass"

# Disable Jekyll processing of assets
keep_files:
  - assets

# Include all files
include:
  - _config.yml
  - assets
  - "*.html"
  - "*.js"
  - "*.css"

# Exclude unwanted files
exclude:
  - node_modules
  - client
  - server  
  - shared
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json

# Plugins
plugins:
  - jekyll-relative-links

# Relative links
relative_links:
  enabled: true
  collections: false