version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cybersec_tools
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cybersec_tools
      - PORT=5000
      - JWT_SECRET=development-jwt-secret
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
      - /app/node_modules
      - /app/server/node_modules
    command: npm run dev

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - server
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
      - /app/node_modules
      - /app/client/node_modules

volumes:
  postgres_data: